name: optimized_cached_image
description: A library for loading images from network, resizing as per container size and caching while being memory sensitive.
version: 3.0.2
homepage: https://github.com/humblerookie/optimized_cached_image

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: 3.3.1
  flutter_image_compress: 2.1.0
  uuid: 4.2.1
  http: ^0.13.5
  path_provider: 2.1.1
  path: 1.8.3
  pedantic: ^1.11.0
  sprintf: 7.0.0
  octo_image: 2.0.0
  image: 4.1.3
  file: ^6.1.2
  flutter_blurhash: ^0.8.2
dev_dependencies:
  test: ^1.24.9